POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Maicon Miranda de Jesus", 
    "email": "maicon@teste.com",
    "password": "senha123"
}

###

POST http://localhost:3003/user/
Content-Type: application/json

{
    "email": "maicon@teste.com",
    "password": "senha123"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxZTg5ZDc4LTZkOWEtNGM3MC1iMzY3LWY5ODRlODgzYjY3ZiIsImlhdCI6MTY4Mjk4ODg0MiwiZXhwIjoxNjgyOTkyNDQyfQ.fl3OSV1JV5TMIr9W1w4iScg43-FEGsgrEYubcE6kSn8