POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Gisela de Souza Abrahão Miranda", 
    "email": "gisela@teste.com",
    "password": "senha123"
}

###

POST http://localhost:3003/user/
Content-Type: application/json

{
    "email": "gisela@teste.com",
    "password": "senha123"
}

###

GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI5ZjA5ODRhLWVlODYtNDIwZS1iOGUwLTMwOTQ3ZjE5MGJhNCIsImlhdCI6MTY4NjMxNTU2OSwiZXhwIjoxNjg2MzE5MTY5fQ.zpdoncFEej7p7VE-sgHBAEuIcBb1XuHw6QdT9FdCRfU